name: webview
description: flutter plugin webview demo

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^3.0.4
  path_provider: ^2.0.11
  rflutter_alert: ^2.0.4
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/www/index.html
    - assets/www/style.css
